// Generated by CoffeeScript 1.3.3
(function() {

  Backbone.sync = Nimbus.backbone_sync;

  Nimbus.Auth.setup("Dropbox", "FZgwco02FGA=|ss/gU/fFo9o+i/ZI7eAVpmnKHtVO1g6Wy72OTwOQPA==, "todomvc_app");

  if (Nimbus.Auth.authorized()) {
    $("#loading").fadeOut();
  }

  Nimbus.Auth.authorized_callback = function() {
    if (Nimbus.Auth.authorized()) {
      return $("#loading").fadeOut();
    }
  };

}).call(this);
